[tool.ruff]
lint.select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "UP",  # pyupgrade
  "I",   # organize imports
  "D",   # docstyle
]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint.pydocstyle]
convention = "google"

[[tool.mypy.overrides]]
module = "harmony_service_lib.*"
ignore_missing_imports = true

[tool.pytest.ini_options]
# Thread on the first warning:
# https://github.com/Unidata/netcdf4-python/issues/1354
# answer about overriding numpy's explicit ignoring warnings
# https://github.com/Unidata/netcdf4-python/issues/1354#issuecomment-2546768878
# https://github.com/numpy/numpy/blob/main/numpy/__init__.py#L320-L323
filterwarnings = [
    "ignore:numpy.ndarray size changed",
    # this warning is pulled deep in pyproj.
    "ignore:You will likely lose important projection information:UserWarning:pyproj.*",
]
