# This is a GitHub action to run mypy on the repository
name: Run mypy

on:
  workflow_call

jobs:
  mypy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12']

    steps:
    - name: Check out harmony-SMAP-L2-gridding-service code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy
        pip install -r pip_requirements.txt -r tests/pip_test_requirements.txt

    - name: Run mypy
      run: mypy .
