# This workflow will build and publish Docker image to ghcr.io

# This workflow runs when changes are detected in the `main` branch, which
# include an update to the `docker/service_version.txt` file.  The workflow can
# also be manually triggered by a repository maintainer.

# IF all pre-requisite tests pass, this workflow will build the docker images,
# push them to ghcr.io and publish a GitHub release.
name: Publish Harmony SMAP L2 Gridding Service

on:
  push:
    branches: [ main ]
    paths: docker/service_version.txt
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository_owner }}/harmony-smap-l2-gridder
  REGISTRY: ghcr.io

jobs:
  run_service_tests:
    uses: ./.github/workflows/run_service_tests.yml

  run_lib_tests:
    uses: ./.github/workflows/run_lib_tests.yml

  mypy:
    uses: ./.github/workflows/mypy.yml

  build_and_publish:
    needs: [run_service_tests, run_lib_tests, mypy]
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # write permission is required to create a GitHub release
      contents: write
      id-token: write
      packages: write
    strategy:
      fail-fast: false

    steps:
      - name: Checkout Harmony-SMAP-L2-gridding-service repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Extract semantic version number
        run: echo "semantic_version=$(cat docker/service_version.txt)" >> $GITHUB_ENV

      - name: Extract release version notes
        run: |
          version_release_notes=$(./bin/extract-release-notes.sh)
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "${version_release_notes}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Log-in to ghcr.io registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add tags to the Docker image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{ env.semantic_version }}

      - name: Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/service.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Publish GitHub release
        uses: ncipollo/release-action@v1
        with:
          body: ${{ env.RELEASE_NOTES }}
          commit: main
          name: Version ${{ env.semantic_version }}
          tag: ${{ env.semantic_version }}
