# This workflow will run when a PR is opened against the `main` branch.
#
# It will trigger the reusable workflows:
#   `.github/workflows/mypy.yml` - which runs mypy on the repository.
#
name: Tests for PRs to main

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_test_service:
    uses: ./.github/workflows/run_service_tests.yml

  run_lib_tests:
    uses: ./.github/workflows/run_lib_tests.yml

  mypy:
    uses: ./.github/workflows/mypy.yml
